version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - backend-network

  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
